### ISSUE TITLE
Error in "createGIFAsynchronouslyForTimePoints"

### ISSUE THREAD

**Issue by GabiFitcal** [matthewpalmer/Regift#17]
I have a error at this line : 
" generator.generateCGImagesAsynchronouslyForTimePoints(timePoints, completionHandler: generationHandler)" from class frunc "createGIFAsynchronouslyForTimePoints".
The message error is:
"<'AVAssetImageGenerator' does not have a member named 'generateCGImagesAsynchronouslyForTimePoints'>"

**Comment by LaChrome** [comment]
I get this error as well.
Xcode 6.4
iOS SDK 8.4

**Comment by matthewpalmer** [comment]
Hmm interesting. It [should definitely be there](https://developer.apple.com/library/mac/documentation/AVFoundation/Reference/AVAssetImageGenerator_Class/#//apple_ref/occ/instm/AVAssetImageGenerator/generateCGImagesAsynchronouslyForTimes:completionHandler:). Am I/are you missing an `import AVFoundation` or something like that?

**Comment by LaChrome** [comment]
Hi Matt,

I found that the issue comes up when adding the project as a git submodule with:
git submodule add https://github.com/matthewpalmer/Regift.git

Then the line of code that causes the issue is present:

generator.generateCGImagesAsynchronouslyForTimePoints(timePoints, completionHandler: generationHandler)" from class frunc "createGIFAsynchronouslyForTimePoints".

"generateCGImagesAsynchronouslyForTimePoints" isn't a function of AVFoundation (I've checked the iOS docs).

If I don't add the project as a git submodule, and just download the latest commit, then manually drag the Regift project into my project, then the issue causing line of code "generateCGImagesAsynchronouslyForTimePoints" isn't present.

It appears to be an issue when adding the Regift repository as a git submodule. It must be defaulting to a older commit? (I'm just assuming this since I haven't checked the older commit's for "generateCGImagesAsynchronouslyForTimePoints".

**Comment by matthewpalmer** [comment]
Hmm that's interesting. I'm not sure what the root cause is, and I'm not supporting adding as a submodule in Swift 2. I've removed those instructions from the README, and Swift 2 changes are now in master.

If you see this issue in master for Cocoapods installation, please let me know :)

Thanks for your help!
